"""Initial migration for integration adapters

Revision ID: 63edcb038ef9
Revises: 
Create Date: 2025-11-29 16:54:10.399444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63edcb038ef9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_providers',
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='alpha', nullable=False),
    sa.Column('capabilities', database.models.JSONType(), nullable=False),
    sa.Column('api_version', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_table('integration_connections',
    sa.Column('connection_id', database.models.GUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('auth_ref', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending_verification', nullable=False),
    sa.Column('enabled_capabilities', database.models.JSONType(), nullable=False),
    sa.Column('metadata_tags', database.models.JSONType(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['integration_providers.provider_id'], ),
    sa.PrimaryKeyConstraint('connection_id')
    )
    op.create_index('idx_connections_status', 'integration_connections', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_connections_tenant_provider', 'integration_connections', ['tenant_id', 'provider_id'], unique=False)
    op.create_index(op.f('ix_integration_connections_tenant_id'), 'integration_connections', ['tenant_id'], unique=False)
    op.create_table('adapter_events',
    sa.Column('event_id', database.models.GUID(), nullable=False),
    sa.Column('connection_id', database.models.GUID(), nullable=False),
    sa.Column('provider_event_type', sa.String(length=255), nullable=False),
    sa.Column('received_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw_payload_ref', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.connection_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_adapter_events_connection', 'adapter_events', ['connection_id', 'received_at'], unique=False)
    op.create_table('normalised_actions',
    sa.Column('action_id', database.models.GUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('connection_id', database.models.GUID(), nullable=False),
    sa.Column('canonical_type', sa.String(length=255), nullable=False),
    sa.Column('target', database.models.JSONType(), nullable=False),
    sa.Column('payload', database.models.JSONType(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.connection_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index('idx_normalised_actions_connection', 'normalised_actions', ['connection_id', 'status'], unique=False)
    op.create_index('idx_normalised_actions_idempotency', 'normalised_actions', ['idempotency_key'], unique=False)
    op.create_index('idx_normalised_actions_tenant', 'normalised_actions', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_normalised_actions_tenant_id'), 'normalised_actions', ['tenant_id'], unique=False)
    op.create_table('polling_cursors',
    sa.Column('cursor_id', database.models.GUID(), nullable=False),
    sa.Column('connection_id', database.models.GUID(), nullable=False),
    sa.Column('cursor_position', sa.Text(), nullable=True),
    sa.Column('last_polled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.connection_id'], ),
    sa.PrimaryKeyConstraint('cursor_id')
    )
    op.create_index('idx_polling_cursors_connection', 'polling_cursors', ['connection_id'], unique=False)
    op.create_table('webhook_registrations',
    sa.Column('registration_id', database.models.GUID(), nullable=False),
    sa.Column('connection_id', database.models.GUID(), nullable=False),
    sa.Column('public_url', sa.String(length=500), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=False),
    sa.Column('events_subscribed', database.models.JSONType(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.connection_id'], ),
    sa.PrimaryKeyConstraint('registration_id')
    )
    op.create_index('idx_webhook_registrations_connection', 'webhook_registrations', ['connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_webhook_registrations_connection', table_name='webhook_registrations')
    op.drop_table('webhook_registrations')
    op.drop_index('idx_polling_cursors_connection', table_name='polling_cursors')
    op.drop_table('polling_cursors')
    op.drop_index(op.f('ix_normalised_actions_tenant_id'), table_name='normalised_actions')
    op.drop_index('idx_normalised_actions_tenant', table_name='normalised_actions')
    op.drop_index('idx_normalised_actions_idempotency', table_name='normalised_actions')
    op.drop_index('idx_normalised_actions_connection', table_name='normalised_actions')
    op.drop_table('normalised_actions')
    op.drop_index('idx_adapter_events_connection', table_name='adapter_events')
    op.drop_table('adapter_events')
    op.drop_index(op.f('ix_integration_connections_tenant_id'), table_name='integration_connections')
    op.drop_index('idx_connections_tenant_provider', table_name='integration_connections')
    op.drop_index('idx_connections_status', table_name='integration_connections')
    op.drop_table('integration_connections')
    op.drop_table('integration_providers')
    # ### end Alembic commands ###
